export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const SET_APP_LANGUAGE = "SET_APP_LANGUAGE";
export const SET_LOGIN_DETAILS = "SET_LOGIN_DETAILS";
export const SET_USER_PROFILE = "SET_USER_PROFILE"
export const SET_SERVICE_LOADER = "SET_SERVICE_LOADER"
export const SET_ACCOUNT_INFO = "SET_ACCOUNT_INFO";
export const SET_IDENTITY_INFO = "SET_IDENTITY_INFO"
export const SET_SELFIE_IMAGE = "SET_SELFIE_IMAGE" 
export const SET_FRONT_IMAGE = "SET_FRONT_IMAGE"
export const SET_BACK_IMAGE = "SET_BACK_IMAGE"
export const SET_SIGNATURE = "SET_SIGNATURE" 
export const SET_ADDRESS_INFO = "SET_ADDRESS_INFO" 
export const SET_BASIC_INFO = "SET_BASIC_INFO" 
export const SET_ADDITIONAL_INFO = "SET_ADDITIONAL_INFO"
export const SET_FAMILY_INFO = "SET_FAMILY_INFO" 
export const SET_MOBILE_NUMBER =  "SET_MOBILE_NUMBER"
export const SET_EMAIL = "SET_EMAIL"







